sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latex-xcolor texlive-pictures
script:
- pdflatex -interaction=nonstopmode -halt-on-error resume.tex
deploy:
  provider: releases
  file:
  - resume.pdf
  skip_cleanup: true
