dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latex-xcolor
  texlive-pictures pgf lmodern
script:
- make
deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _build/
