sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latex-xcolor
  texlive-pictures pgf lmodern
script:
- pdflatex -interaction=nonstopmode -halt-on-error resume.tex
deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: X1b3KllddK5LyQVaivtdMbZPmc4Aa2xnuFQ79wEQUl/eIdlDSYt1Irl4nFTBBa/GHTSNsb9bUIMOlRVfbBDUa2HhUPE1hfiY4F7MaNH8zwJ0P4q2+2WYN8wI7FOB9Y5sdJVln7XRBE4hcgbujDXl2HGPMlsQy7J7f6aPXmO7ivgK9lPNnfSrfuAzYe9z9nofe1MoegkI4AmatvIw97I9RNIbXL5gLpClQiwtSjGcN+RgGpOIqQzrjj1tblqviOxUvfUIA5ZLB+rvmpSgGUYQPjQY/RnsQV/iDn6hNpn3E/YbWbLL9YI83j/goC1I41GeO3WR7KzJxTK4B1zJTCYpxS6iNXQanqOteSX2sob8Sm4EyIver+Cw5ZWM3XB2uhjA3v00v67R00Ln5EIz0qgE/19z2McOQbCHjz4VqVj1UYGibvBe58v5DbaxNwqpVqvYG5IRcbhisSQa+7AmQilr9wkJbrOP2djIFaxuYhFfbjKsXO6KPm/4qVU7JX+gNTW4/SNGfiP/WZlYWvjfkB+O/rj128aBAw2hUJx8GjM0ZBhMrsc7BDhO2GQ5Pr+wqJe12O007wD5wIC8B7imuc781tTq6KnzXmdGxkFZMtR5JCsd6mhn0C3Y24xm29T2S8hVLlVECD6Cnh4yBcPCTGYllLAf/3WIE2+7Ru/2e84FMz8=
$GITHUB_TOKEN
  keep-history: true
  on:
    branch: master