name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
      - name: Compile English LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume_en.tex
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'ref/head/master' }}
        id: deployment
        uses: actions/deploy-pages@v4
    permissions:
        pages: write
        id-token: write
